# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zheng Zhi Hao
email: 784716740@qq.com
description: "this is my blog"
affiliation: 中山大学南方学院 <a href = 'http://wcy.nfu.edu.cn/zh/教学教务/培养方案/网络与新媒体/'>网络与新媒体</a> 培养方案核心课程学期作品，由 <a href='http://wcy.nfu.edu.cn/zh/学院概况/师资队伍/廖汉腾/'>廖汉腾副教授</a> 指导
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ch-CN"
locale: zh_CN # 本地化翻譯
url: "www.zhihaopy.github.io" # the base hostname & protocol for your site
twitter_username: hao ge
github_username:  zhihaopy
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

# Site owner
owner:
  name: zhihao大哥
  email: 784716740@qq.com
  twitter: hello
  google:
    ad-client:
    ad-slot:
  bio: "社会你豪哥"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:
